# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               My Example Blog
tagline:             Just another hello world
url:                 http://www.example.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Your Namehere
  url:               https://twitter.com/example
  email:             example@example.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
